### ISSUE TITLE
Add Ruckingenur (non-Steam game) (edited title)

### ISSUE THREAD

**Issue by akoerner** [arcataroger/awesome-engineering-games#1]
https://www.zachtronics.com/ruckingenur-ii/

**Comment by eternaleclipse** [comment]
Anything by Zachtronics is amazing. I have been following and enjoying his work since his flash game "Codex of Alchemical Engineering".

**Comment by arcataroger** [comment]
Hey @akoerner and @eternaleclipse, thanks for the suggestion!

So far the list only includes Steam games, but that doesn't have to stay the case. I just started a new discussion on this here: https://github.com/arcataroger/awesome-engineering-games/discussions/15

Could you please contribute some thoughts there? Let's give it a few days and see what the community thinks?

Thanks!

**Comment by arcataroger** [comment]
Just an update: We waited a while for feedback, but didn't get much: https://github.com/arcataroger/awesome-engineering-games/discussions/15#discussioncomment-7721564

So far my inclination is to keep the list Steam-only, if only for cleanliness and ease of use (i.e. not having to open it up to emulators, DOSbox, compile-from-source games, etc.). It also creates somewhat of a curation headache there because there's no easy way to vouch for their "awesomeness", vs having a record of their reviews.

I think it would be great to make a sister list showing all the potential non-Steam games though, both like Ruckingenur but also OpenTTD, etc., if anyone wants to take that on. The curation criteria would be different but that's ok. I'd be happy to link to it from this list too.

For this list, however, I'm going to close this issue in a few days unless anyone has strong objections and wants to argue for a different approach :)
